// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjt7YkvRXiUuFSNiTEY0cIkC-AVuPox4',
    appId: '1:964646589740:web:2a85236a70ea4bcfc78889',
    messagingSenderId: '964646589740',
    projectId: 'ravita-nexus',
    authDomain: 'ravita-nexus.firebaseapp.com',
    storageBucket: 'ravita-nexus.firebasestorage.app',
    measurementId: 'G-922XBEWKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvBZAARGBf6ci6U3asJhqwEEUDThbqE8',
    appId: '1:964646589740:android:d567bddf13f04c10c78889',
    messagingSenderId: '964646589740',
    projectId: 'ravita-nexus',
    storageBucket: 'ravita-nexus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFpLB9K2wC3IitC7qen53fPaVKrytmAs',
    appId: '1:964646589740:ios:d1ba0cdf8939e104c78889',
    messagingSenderId: '964646589740',
    projectId: 'ravita-nexus',
    storageBucket: 'ravita-nexus.firebasestorage.app',
    iosBundleId: 'com.example.ravitaNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyFpLB9K2wC3IitC7qen53fPaVKrytmAs',
    appId: '1:964646589740:ios:d1ba0cdf8939e104c78889',
    messagingSenderId: '964646589740',
    projectId: 'ravita-nexus',
    storageBucket: 'ravita-nexus.firebasestorage.app',
    iosBundleId: 'com.example.ravitaNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVjt7YkvRXiUuFSNiTEY0cIkC-AVuPox4',
    appId: '1:964646589740:web:35528f89a2412ed0c78889',
    messagingSenderId: '964646589740',
    projectId: 'ravita-nexus',
    authDomain: 'ravita-nexus.firebaseapp.com',
    storageBucket: 'ravita-nexus.firebasestorage.app',
    measurementId: 'G-MCMYF8SHRY',
  );
}
