// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ihEda2SyjQGP0X6qlcJZtH3fEEbETWo',
    appId: '1:854556457899:web:0c3bb3ce49bf85ef6fb0ee',
    messagingSenderId: '854556457899',
    projectId: 'aerie-box',
    authDomain: 'aerie-box.firebaseapp.com',
    storageBucket: 'aerie-box.firebasestorage.app',
    measurementId: 'G-ZJXGBP2MEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Tr4tiWKjWJQbSWtbJnytgNBIaSCjICs',
    appId: '1:854556457899:android:287b1a031e98126e6fb0ee',
    messagingSenderId: '854556457899',
    projectId: 'aerie-box',
    storageBucket: 'aerie-box.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2lnK9M1JQRRP3gRe77iNPGlY7ikWvbY',
    appId: '1:854556457899:ios:d536fd6be3dc88016fb0ee',
    messagingSenderId: '854556457899',
    projectId: 'aerie-box',
    storageBucket: 'aerie-box.firebasestorage.app',
    iosBundleId: 'com.example.ravitaNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-2lnK9M1JQRRP3gRe77iNPGlY7ikWvbY',
    appId: '1:854556457899:ios:d536fd6be3dc88016fb0ee',
    messagingSenderId: '854556457899',
    projectId: 'aerie-box',
    storageBucket: 'aerie-box.firebasestorage.app',
    iosBundleId: 'com.example.ravitaNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ihEda2SyjQGP0X6qlcJZtH3fEEbETWo',
    appId: '1:854556457899:web:ac2a16c5661684996fb0ee',
    messagingSenderId: '854556457899',
    projectId: 'aerie-box',
    authDomain: 'aerie-box.firebaseapp.com',
    storageBucket: 'aerie-box.firebasestorage.app',
    measurementId: 'G-V121VEMP9Q',
  );
}
